language: go
stages:
  - lint
  - test
go:
  - 1.x

jobs:
  include:
    - stage: lint
      install:
        - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      script:
        - make lint
    - stage: test
      script:
        - make test
    - stage: test
      os: windows
      script:
        - go test
    - stage: test
      os: osx
      script:
        - make test
