// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tagatac/gorecurcopy (interfaces: Copier)

// Package mock_gorecurcopy is a generated GoMock package.
package mock_gorecurcopy

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCopier is a mock of Copier interface.
type MockCopier struct {
	ctrl     *gomock.Controller
	recorder *MockCopierMockRecorder
}

// MockCopierMockRecorder is the mock recorder for MockCopier.
type MockCopierMockRecorder struct {
	mock *MockCopier
}

// NewMockCopier creates a new mock instance.
func NewMockCopier(ctrl *gomock.Controller) *MockCopier {
	mock := &MockCopier{ctrl: ctrl}
	mock.recorder = &MockCopierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCopier) EXPECT() *MockCopierMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockCopier) Copy(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockCopierMockRecorder) Copy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockCopier)(nil).Copy), arg0, arg1)
}

// CopyDirectory mocks base method.
func (m *MockCopier) CopyDirectory(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyDirectory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyDirectory indicates an expected call of CopyDirectory.
func (mr *MockCopierMockRecorder) CopyDirectory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyDirectory", reflect.TypeOf((*MockCopier)(nil).CopyDirectory), arg0, arg1)
}

// CopySymLink mocks base method.
func (m *MockCopier) CopySymLink(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopySymLink", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopySymLink indicates an expected call of CopySymLink.
func (mr *MockCopierMockRecorder) CopySymLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopySymLink", reflect.TypeOf((*MockCopier)(nil).CopySymLink), arg0, arg1)
}
